version: "3.9"
services:
  forwarder:
    build: ./forwarder
    volumes:
      # dnsmasq
      - ./forwarder/contents/dnsmasq.conf:/etc/dnsmasq.conf
      # BIND9
      # - ./forwarder/contents/named.conf:/var/named/chroot/etc/named.conf
      # Unbound
      # - ./forwarder/contents/unbound.conf:/usr/local/etc/unbound/unbound.conf
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 10.0.0.2
  auth:
    build: ./auth
    volumes:
      - ./auth/contents:/app
      - ./log-volume:/logs
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 10.0.0.3
  attacker:
    build: ./attacker
    command: tail -f /dev/null
    volumes:
      - ./attacker/contents:/app
      - ./log-volume:/logs
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 10.0.0.4
networks:
  app_net:
    ipam:
      config:
        - subnet: 10.0.0.0/24